import { expect, test } from '@playwright/test';

test('Полный сценарий: конструктор → публикация → предложение → решение бизнеса', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Мои задачи', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Создать задачу' }).click();
  await page.getByLabel('Название задачи').fill('Браузерный сценарий: аналитика обращений');
  await page.getByLabel('Краткое описание').fill('Нужно ускорить обработку обращений клиентов.');
  await page.getByRole('button', { name: 'Далее' }).click();
  await page.locator('textarea[name="context"]').fill('Операторы вручную распределяют 100 обращений каждый день.');
  await page.locator('textarea[name="materials"]').fill('Есть обезличенная выгрузка заявок в CSV.');
  await page.getByRole('button', { name: 'Сформировать карточку' }).click();
  await expect(page.getByText('Операторы вручную распределяют 100 обращений каждый день.', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Назад', exact: true }).click();
  await expect(page.locator('textarea[name="materials"]')).toHaveValue('Есть обезличенная выгрузка заявок в CSV.');
  await page.getByRole('button', { name: 'Сформировать карточку' }).click();
  await page.getByRole('button', { name: 'Далее' }).click();
  await page.getByLabel('Ожидаемый результат', { exact: true }).fill('Прототип классификатора обращений и отчёт о точности.');
  await page.getByRole('button', { name: 'Подтвердить карточку' }).click();
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '55');
  await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
  await expect(page.getByText('Опубликована', { exact: true })).toBeVisible();
  const taskHash = new URL(page.url()).hash;
  await page.getByRole('button', { name: 'Редактировать', exact: true }).click();
  await page.getByLabel('Ожидаемый результат', { exact: true }).fill('Обновлённый прототип и отчёт о качестве классификации.');
  await page.getByRole('button', { name: 'Сохранить и выйти' }).click();
  await expect(page.getByRole('button', { name: 'Опубликовать', exact: true })).toBeDisabled();
  await expect(page.getByText('Ожидает вашего подтверждения')).toBeVisible();
  await page.getByRole('button', { name: 'Подтвердить карточку' }).click();
  await expect(page.getByRole('button', { name: 'Опубликовать', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
  await expect(page.getByText('Опубликована', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Студент', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Поиск задач' }).fill('Браузерный сценарий');
  await page.getByRole('button', { name: 'Подробнее' }).click();
  await page.locator('.proposal-form').getByLabel('Демонстрационная команда').selectOption('2');
  await page.getByLabel('Сообщение бизнесу').fill('Наша команда готова помочь с обработкой обращений.');
  await page.getByLabel('Предлагаемое решение').fill('Разметим выборку, обучим модель и проверим качество на отложенных данных.');
  await page.getByRole('button', { name: 'Отправить предложение' }).click();
  await expect(page.getByText('На рассмотрении', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Мои предложения' }).click();
  await expect(page.getByRole('heading', { name: 'Мои предложения', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Браузерный сценарий: аналитика обращений', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Бизнес', exact: true }).click();
  await page.getByRole('link', { name: 'Предложения', exact: true }).click();
  const proposal = page.locator('.proposal-card').filter({ hasText: 'Браузерный сценарий: аналитика обращений' });
  await proposal.getByRole('button', { name: 'Принять', exact: true }).click();
  await expect(proposal.getByText('Принято', { exact: true })).toBeVisible();
  await expect(proposal.getByRole('button', { name: 'Принять', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(proposal.getByText('Принято', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Студент', exact: true }).click();
  await page.goto(`/${taskHash}`);
  await expect(page.getByText('Принято', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/task-detail-desktop.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('Нулевой рейтинг не мешает публикации через интерфейс', async ({ page }) => {
  await page.goto('/#new');
  await page.getByLabel('Название задачи').fill('Задача с нулевым рейтингом');
  await page.getByLabel('Краткое описание').fill('Детали уточним вместе с командой.');
  await page.getByRole('button', { name: 'Далее' }).click();
  await page.getByRole('button', { name: 'Сформировать карточку' }).click();
  await page.getByRole('button', { name: 'Далее' }).click();
  await page.getByRole('button', { name: 'Подтвердить карточку' }).click();
  await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '0');
  await page.getByRole('button', { name: 'Опубликовать', exact: true }).click();
  await expect(page.getByText('Опубликована', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Студент', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Поиск задач' }).fill('Задача с нулевым рейтингом');
  await expect(page.getByRole('button', { name: 'Задача с нулевым рейтингом', exact: true })).toBeVisible();
});

test('Каталог, фильтры, команды, отказ и мобильная навигация без ошибок', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Студент', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Каталог задач' })).toBeVisible();
  await page.getByLabel('Уровень готовности').selectOption('Приоритетная');
  await expect(page.locator('.task-card')).toHaveCount(1);
  await page.getByLabel('Уровень готовности').selectOption('');
  await page.getByRole('searchbox', { name: 'Поиск задач' }).fill('НЕСУЩЕСТВУЮЩИЙ ЗАПРОС');
  await expect(page.getByRole('heading', { name: 'Задачи не найдены' })).toBeVisible();
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click();
  await page.getByLabel('Сортировка').selectOption('score_asc');
  await expect(page.locator('.task-card').first().getByRole('progressbar')).toHaveAttribute('aria-valuenow', /^(0|10)$/);
  await page.screenshot({ path: 'test-results/catalog-desktop.png', fullPage: true });
  await page.getByRole('link', { name: 'Команды', exact: true }).click();
  await expect(page.locator('.team-card')).toHaveCount(5);
  await page.getByRole('button', { name: 'Профиль команды' }).first().click();
  await expect(page.getByRole('heading', { name: 'Профиль команды' })).toBeVisible();
  await page.getByRole('link', { name: 'Мои предложения' }).click();
  await page.getByLabel('Демонстрационная команда').selectOption('5');
  await expect(page.getByText('Анализ энергопотребления', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Бизнес', exact: true }).click();
  await page.getByRole('link', { name: 'Предложения', exact: true }).click();
  const proposal = page.locator('.proposal-card').filter({ hasText: 'Анализ энергопотребления' });
  await proposal.getByRole('button', { name: 'Отклонить', exact: true }).click();
  await expect(proposal.getByText('Отклонено', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Студент', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Каталог задач' })).toBeVisible();
  await expect(page.locator('.task-card').first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/catalog-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Подробнее' }).first().click();
  await expect(page.getByRole('heading', { name: 'Ваше предложение', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('Ошибка сети видна пользователю и запрос можно повторить', async ({ page }) => {
  await page.route('**/api/tasks?**', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: '{}' }));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Не удалось загрузить данные' })).toBeVisible();
  await page.unroute('**/api/tasks?**');
  await page.getByRole('button', { name: 'Повторить', exact: true }).click();
  await expect(page.locator('.task-card').first()).toBeVisible();
});
